python main.py --mode train-all \
               --dataset-path ./data/splited \
               --workers 4 \
               --epochs 20 \
               --num-classes 16 \
               --num-samples 1 \
               --use-augmentation \
               --use-pretrained \
               --lr 1e-2 \
               --attention \
               --scheduler MultiStepLR \
               --save-dir ./model/facenet_seresnext \
               --gpu 0 
